/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_wndMain (void);
GtkWidget* create_wndTorque (void);
GtkWidget* create_wndWheelForce (void);
GtkWidget* create_wndTime (void);
GtkWidget* create_wndPerf (void);
GtkWidget* create_wndImgGraph (void);
