/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_wndMain (void)
{
  GtkWidget *wndMain;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem1;
  GtkWidget *menuitem1_menu;
  GtkWidget *nowy1;
  GtkWidget *otw__rz1;
  GtkWidget *zapisz1;
  GtkWidget *zapisz_jako1;
  GtkWidget *separatormenuitem1;
  GtkWidget *zako__cz1;
  GtkWidget *menuitem2;
  GtkWidget *menuitem2_menu;
  GtkWidget *wytnij1;
  GtkWidget *skopiuj1;
  GtkWidget *wklej1;
  GtkWidget *usu__1;
  GtkWidget *menuitem3;
  GtkWidget *menuitem3_menu;
  GtkWidget *graph_image_window1;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *informacje_o1;
  GtkWidget *hbox6;
  GtkWidget *label84;
  GtkObject *spinWeight_adj;
  GtkWidget *spinWeight;
  GtkWidget *hseparator8;
  GtkWidget *hbox1;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkObject *spinMinRpm_adj;
  GtkWidget *spinMinRpm;
  GtkWidget *label3;
  GtkObject *spinMaxRpm_adj;
  GtkWidget *spinMaxRpm;
  GtkWidget *btnUpdate;
  GtkWidget *hbox2;
  GtkWidget *label28;
  GtkWidget *lblMaxTorque;
  GtkWidget *label30;
  GtkWidget *lblMaxHP;
  GtkWidget *hseparator1;
  GtkWidget *expander2;
  GtkWidget *vbox9;
  GtkWidget *table1;
  GtkObject *spinGear1_adj;
  GtkWidget *spinGear1;
  GtkObject *spinGear2_adj;
  GtkWidget *spinGear2;
  GtkObject *spinGear3_adj;
  GtkWidget *spinGear3;
  GtkObject *spinGear4_adj;
  GtkWidget *spinGear4;
  GtkObject *spinGear5_adj;
  GtkWidget *spinGear5;
  GtkObject *spinGear6_adj;
  GtkWidget *spinGear6;
  GtkObject *spinGear7_adj;
  GtkWidget *spinGear7;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkWidget *scaleGears;
  GtkWidget *label5;
  GtkWidget *label17;
  GtkWidget *label16;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *lblVMin1;
  GtkWidget *lblVMin3;
  GtkWidget *lblVMin4;
  GtkWidget *lblVMin5;
  GtkWidget *lblVMin6;
  GtkWidget *lblVMin7;
  GtkWidget *lblVMax7;
  GtkWidget *lblVMax6;
  GtkWidget *lblVMax5;
  GtkWidget *lblVMax4;
  GtkWidget *lblVMax3;
  GtkWidget *lblVMax2;
  GtkWidget *lblVMax1;
  GtkWidget *lblVMin2;
  GtkWidget *hseparator2;
  GtkWidget *table3;
  GtkWidget *label27;
  GtkObject *spinDiffer_adj;
  GtkWidget *spinDiffer;
  GtkWidget *label26;
  GtkWidget *label95;
  GtkWidget *hseparator9;
  GtkWidget *expander3;
  GtkWidget *table2;
  GtkWidget *label23;
  GtkWidget *label25;
  GtkObject *spinTireWidth_adj;
  GtkWidget *spinTireWidth;
  GtkWidget *label31;
  GtkObject *spinTireRatio_adj;
  GtkWidget *spinTireRatio;
  GtkWidget *label24;
  GtkObject *spinRim_adj;
  GtkWidget *spinRim;
  GtkWidget *label32;
  GtkWidget *lblWheelHeight;
  GtkWidget *label33;
  GtkWidget *lblWheelPerimeter;
  GtkWidget *label96;
  GtkWidget *sbMain;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  wndMain = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (wndMain), _("Torque symulator"));
  gtk_window_set_resizable (GTK_WINDOW (wndMain), FALSE);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (wndMain), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  menuitem1 = gtk_menu_item_new_with_mnemonic (_("_Plik"));
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem1);

  menuitem1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menuitem1_menu);

  nowy1 = gtk_image_menu_item_new_from_stock ("gtk-new", accel_group);
  gtk_widget_show (nowy1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), nowy1);

  otw__rz1 = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_show (otw__rz1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), otw__rz1);

  zapisz1 = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_show (zapisz1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), zapisz1);

  zapisz_jako1 = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_show (zapisz_jako1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), zapisz_jako1);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  zako__cz1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (zako__cz1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), zako__cz1);

  menuitem2 = gtk_menu_item_new_with_mnemonic (_("_Edycja"));
  gtk_widget_show (menuitem2);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem2);

  menuitem2_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem2), menuitem2_menu);

  wytnij1 = gtk_image_menu_item_new_from_stock ("gtk-cut", accel_group);
  gtk_widget_show (wytnij1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), wytnij1);

  skopiuj1 = gtk_image_menu_item_new_from_stock ("gtk-copy", accel_group);
  gtk_widget_show (skopiuj1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), skopiuj1);

  wklej1 = gtk_image_menu_item_new_from_stock ("gtk-paste", accel_group);
  gtk_widget_show (wklej1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), wklej1);

  usu__1 = gtk_image_menu_item_new_from_stock ("gtk-delete", accel_group);
  gtk_widget_show (usu__1);
  gtk_container_add (GTK_CONTAINER (menuitem2_menu), usu__1);

  menuitem3 = gtk_menu_item_new_with_mnemonic (_("_Widok"));
  gtk_widget_show (menuitem3);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem3);

  menuitem3_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem3), menuitem3_menu);

  graph_image_window1 = gtk_menu_item_new_with_mnemonic (_("Graph image window"));
  gtk_widget_show (graph_image_window1);
  gtk_container_add (GTK_CONTAINER (menuitem3_menu), graph_image_window1);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("Pomo_c"));
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  informacje_o1 = gtk_menu_item_new_with_mnemonic (_("_Informacje o"));
  gtk_widget_show (informacje_o1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), informacje_o1);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox6, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox6), 2);

  label84 = gtk_label_new (_("Weight"));
  gtk_widget_show (label84);
  gtk_box_pack_start (GTK_BOX (hbox6), label84, FALSE, FALSE, 0);

  spinWeight_adj = gtk_adjustment_new (1200, 100, 10000, 0.20000000298, 10, 10);
  spinWeight = gtk_spin_button_new (GTK_ADJUSTMENT (spinWeight_adj), 1, 0);
  gtk_widget_show (spinWeight);
  gtk_box_pack_start (GTK_BOX (hbox6), spinWeight, TRUE, TRUE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinWeight), TRUE);

  hseparator8 = gtk_hseparator_new ();
  gtk_widget_show (hseparator8);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator8, TRUE, TRUE, 0);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox1), 2);

  label1 = gtk_label_new (_("<b>RPM</b>"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);
  gtk_misc_set_padding (GTK_MISC (label1), 6, 0);

  label2 = gtk_label_new (_("Min"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox1), label2, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label2), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_padding (GTK_MISC (label2), 2, 0);

  spinMinRpm_adj = gtk_adjustment_new (1000, 10, 1000, 1, 10, 10);
  spinMinRpm = gtk_spin_button_new (GTK_ADJUSTMENT (spinMinRpm_adj), 1, 0);
  gtk_widget_show (spinMinRpm);
  gtk_box_pack_start (GTK_BOX (hbox1), spinMinRpm, TRUE, TRUE, 0);

  label3 = gtk_label_new (_("Max"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox1), label3, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label3), 2, 0);

  spinMaxRpm_adj = gtk_adjustment_new (7000, 10, 22000, 1, 10, 10);
  spinMaxRpm = gtk_spin_button_new (GTK_ADJUSTMENT (spinMaxRpm_adj), 1, 0);
  gtk_widget_show (spinMaxRpm);
  gtk_box_pack_start (GTK_BOX (hbox1), spinMaxRpm, TRUE, TRUE, 0);

  btnUpdate = gtk_button_new_with_mnemonic (_("Update"));
  gtk_widget_show (btnUpdate);
  gtk_box_pack_start (GTK_BOX (hbox1), btnUpdate, FALSE, FALSE, 0);
  gtk_widget_set_sensitive (btnUpdate, FALSE);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox2, TRUE, TRUE, 0);

  label28 = gtk_label_new (_("<b>Max torque</b>"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox2), label28, TRUE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label28), TRUE);

  lblMaxTorque = gtk_label_new (_("0@0"));
  gtk_widget_show (lblMaxTorque);
  gtk_box_pack_start (GTK_BOX (hbox2), lblMaxTorque, FALSE, FALSE, 0);

  label30 = gtk_label_new (_("<b>Max HP</b>"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox2), label30, TRUE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label30), TRUE);

  lblMaxHP = gtk_label_new (_("0@0"));
  gtk_widget_show (lblMaxHP);
  gtk_box_pack_start (GTK_BOX (hbox2), lblMaxHP, FALSE, FALSE, 0);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator1, TRUE, TRUE, 0);

  expander2 = gtk_expander_new (NULL);
  gtk_widget_show (expander2);
  gtk_box_pack_start (GTK_BOX (vbox1), expander2, FALSE, TRUE, 0);

  vbox9 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox9);
  gtk_container_add (GTK_CONTAINER (expander2), vbox9);

  table1 = gtk_table_new (8, 5, FALSE);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (vbox9), table1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table1), 1);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 2);

  spinGear1_adj = gtk_adjustment_new (1.20000004768, 0.0500000007451, 5, 0.00999999977648, 0.00999999977648, 0);
  spinGear1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinGear1_adj), 1, 3);
  gtk_widget_show (spinGear1);
  gtk_table_attach (GTK_TABLE (table1), spinGear1, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinGear1), TRUE);

  spinGear2_adj = gtk_adjustment_new (1.20000004768, 0.0500000007451, 5, 0.00999999977648, 0.00999999977648, 0);
  spinGear2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinGear2_adj), 1, 3);
  gtk_widget_show (spinGear2);
  gtk_table_attach (GTK_TABLE (table1), spinGear2, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinGear2), TRUE);

  spinGear3_adj = gtk_adjustment_new (1.20000004768, 0.0500000007451, 5, 0.00999999977648, 0.00999999977648, 0);
  spinGear3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinGear3_adj), 1, 3);
  gtk_widget_show (spinGear3);
  gtk_table_attach (GTK_TABLE (table1), spinGear3, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinGear3), TRUE);

  spinGear4_adj = gtk_adjustment_new (1.19000005722, 0.0500000007451, 5, 0.00999999977648, 0.00999999977648, 0);
  spinGear4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinGear4_adj), 1, 3);
  gtk_widget_show (spinGear4);
  gtk_table_attach (GTK_TABLE (table1), spinGear4, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinGear4), TRUE);

  spinGear5_adj = gtk_adjustment_new (1.20000004768, 0.0500000007451, 5, 0.00999999977648, 0.00999999977648, 0);
  spinGear5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinGear5_adj), 1, 3);
  gtk_widget_show (spinGear5);
  gtk_table_attach (GTK_TABLE (table1), spinGear5, 2, 3, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinGear5), TRUE);

  spinGear6_adj = gtk_adjustment_new (1.20000004768, 0.0500000007451, 5, 0.00999999977648, 0.00999999977648, 0);
  spinGear6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinGear6_adj), 1, 3);
  gtk_widget_show (spinGear6);
  gtk_table_attach (GTK_TABLE (table1), spinGear6, 2, 3, 6, 7,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinGear6), TRUE);

  spinGear7_adj = gtk_adjustment_new (1.20000004768, 0.0500000007451, 5, 0.00999999977648, 0.00999999977648, 0);
  spinGear7 = gtk_spin_button_new (GTK_ADJUSTMENT (spinGear7_adj), 1, 3);
  gtk_widget_show (spinGear7);
  gtk_table_attach (GTK_TABLE (table1), spinGear7, 2, 3, 7, 8,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinGear7), TRUE);

  label6 = gtk_label_new (_("ratio"));
  gtk_widget_show (label6);
  gtk_table_attach (GTK_TABLE (table1), label6, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label6), 0.38, 0.5);

  label7 = gtk_label_new (_("V Min"));
  gtk_widget_show (label7);
  gtk_table_attach (GTK_TABLE (table1), label7, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label7), 0, 0.5);

  label8 = gtk_label_new (_("V Max"));
  gtk_widget_show (label8);
  gtk_table_attach (GTK_TABLE (table1), label8, 4, 5, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label8), 0, 0.5);

  scaleGears = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (6, 1, 7, 1, 0, 0)));
  gtk_widget_show (scaleGears);
  gtk_table_attach (GTK_TABLE (table1), scaleGears, 0, 1, 1, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_scale_set_digits (GTK_SCALE (scaleGears), 0);

  label5 = gtk_label_new (_("gear"));
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (table1), label5, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label5), 0, 0.5);

  label17 = gtk_label_new (_("2"));
  gtk_widget_show (label17);
  gtk_table_attach (GTK_TABLE (table1), label17, 1, 2, 2, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label17), 1, 0.5);

  label16 = gtk_label_new (_("1"));
  gtk_widget_show (label16);
  gtk_table_attach (GTK_TABLE (table1), label16, 1, 2, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label16), 1, 0.5);

  label18 = gtk_label_new (_("3"));
  gtk_widget_show (label18);
  gtk_table_attach (GTK_TABLE (table1), label18, 1, 2, 3, 4,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label18), 1, 0.5);

  label19 = gtk_label_new (_("4"));
  gtk_widget_show (label19);
  gtk_table_attach (GTK_TABLE (table1), label19, 1, 2, 4, 5,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label19), 1, 0.5);

  label20 = gtk_label_new (_("5"));
  gtk_widget_show (label20);
  gtk_table_attach (GTK_TABLE (table1), label20, 1, 2, 5, 6,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label20), 1, 0.5);

  label21 = gtk_label_new (_("6"));
  gtk_widget_show (label21);
  gtk_table_attach (GTK_TABLE (table1), label21, 1, 2, 6, 7,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label21), 1, 0.5);

  label22 = gtk_label_new (_("7"));
  gtk_widget_show (label22);
  gtk_table_attach (GTK_TABLE (table1), label22, 1, 2, 7, 8,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label22), 1, 0.5);

  lblVMin1 = gtk_label_new (_("0"));
  gtk_widget_show (lblVMin1);
  gtk_table_attach (GTK_TABLE (table1), lblVMin1, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblVMin1), 1, 0.5);

  lblVMin3 = gtk_label_new (_("0"));
  gtk_widget_show (lblVMin3);
  gtk_table_attach (GTK_TABLE (table1), lblVMin3, 3, 4, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblVMin3), 1, 0.5);

  lblVMin4 = gtk_label_new (_("0"));
  gtk_widget_show (lblVMin4);
  gtk_table_attach (GTK_TABLE (table1), lblVMin4, 3, 4, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblVMin4), 1, 0.5);

  lblVMin5 = gtk_label_new (_("0"));
  gtk_widget_show (lblVMin5);
  gtk_table_attach (GTK_TABLE (table1), lblVMin5, 3, 4, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblVMin5), 1, 0.5);

  lblVMin6 = gtk_label_new (_("0"));
  gtk_widget_show (lblVMin6);
  gtk_table_attach (GTK_TABLE (table1), lblVMin6, 3, 4, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblVMin6), 1, 0.5);

  lblVMin7 = gtk_label_new (_("0"));
  gtk_widget_show (lblVMin7);
  gtk_table_attach (GTK_TABLE (table1), lblVMin7, 3, 4, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblVMin7), 1, 0.5);

  lblVMax7 = gtk_label_new (_("0"));
  gtk_widget_show (lblVMax7);
  gtk_table_attach (GTK_TABLE (table1), lblVMax7, 4, 5, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblVMax7), 1, 0.5);

  lblVMax6 = gtk_label_new (_("0"));
  gtk_widget_show (lblVMax6);
  gtk_table_attach (GTK_TABLE (table1), lblVMax6, 4, 5, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblVMax6), 1, 0.5);

  lblVMax5 = gtk_label_new (_("0"));
  gtk_widget_show (lblVMax5);
  gtk_table_attach (GTK_TABLE (table1), lblVMax5, 4, 5, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblVMax5), 1, 0.5);

  lblVMax4 = gtk_label_new (_("0"));
  gtk_widget_show (lblVMax4);
  gtk_table_attach (GTK_TABLE (table1), lblVMax4, 4, 5, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblVMax4), 1, 0.5);

  lblVMax3 = gtk_label_new (_("0"));
  gtk_widget_show (lblVMax3);
  gtk_table_attach (GTK_TABLE (table1), lblVMax3, 4, 5, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblVMax3), 1, 0.5);

  lblVMax2 = gtk_label_new (_("0"));
  gtk_widget_show (lblVMax2);
  gtk_table_attach (GTK_TABLE (table1), lblVMax2, 4, 5, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblVMax2), 1, 0.5);

  lblVMax1 = gtk_label_new (_("0"));
  gtk_widget_show (lblVMax1);
  gtk_table_attach (GTK_TABLE (table1), lblVMax1, 4, 5, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblVMax1), 1, 0.5);

  lblVMin2 = gtk_label_new (_("0"));
  gtk_widget_show (lblVMin2);
  gtk_table_attach (GTK_TABLE (table1), lblVMin2, 3, 4, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblVMin2), 1, 0.5);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_box_pack_start (GTK_BOX (vbox9), hseparator2, TRUE, TRUE, 0);

  table3 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table3);
  gtk_box_pack_start (GTK_BOX (vbox9), table3, TRUE, TRUE, 0);

  label27 = gtk_label_new (_("ratio"));
  gtk_widget_show (label27);
  gtk_table_attach (GTK_TABLE (table3), label27, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label27), 0, 0.5);

  spinDiffer_adj = gtk_adjustment_new (1.10000002384, 0.5, 20, 0.00999999977648, 0, 0);
  spinDiffer = gtk_spin_button_new (GTK_ADJUSTMENT (spinDiffer_adj), 1, 3);
  gtk_widget_show (spinDiffer);
  gtk_table_attach (GTK_TABLE (table3), spinDiffer, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label26 = gtk_label_new (_("<b>Differential</b>"));
  gtk_widget_show (label26);
  gtk_table_attach (GTK_TABLE (table3), label26, 0, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label26), TRUE);

  label95 = gtk_label_new (_("<b>Gearbox</b>"));
  gtk_widget_show (label95);
  gtk_expander_set_label_widget (GTK_EXPANDER (expander2), label95);
  gtk_label_set_use_markup (GTK_LABEL (label95), TRUE);
  gtk_label_set_justify (GTK_LABEL (label95), GTK_JUSTIFY_CENTER);

  hseparator9 = gtk_hseparator_new ();
  gtk_widget_show (hseparator9);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator9, TRUE, TRUE, 0);

  expander3 = gtk_expander_new (NULL);
  gtk_widget_show (expander3);
  gtk_box_pack_start (GTK_BOX (vbox1), expander3, TRUE, TRUE, 0);

  table2 = gtk_table_new (6, 2, FALSE);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (expander3), table2);
  gtk_container_set_border_width (GTK_CONTAINER (table2), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table2), 2);

  label23 = gtk_label_new (_("<b>Running wheels</b>"));
  gtk_widget_show (label23);
  gtk_table_attach (GTK_TABLE (table2), label23, 0, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label23), TRUE);
  gtk_label_set_justify (GTK_LABEL (label23), GTK_JUSTIFY_CENTER);

  label25 = gtk_label_new (_("tire width (mm)"));
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (table2), label25, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label25), 0, 0.5);

  spinTireWidth_adj = gtk_adjustment_new (185, 10, 500, 1, 10, 10);
  spinTireWidth = gtk_spin_button_new (GTK_ADJUSTMENT (spinTireWidth_adj), 1, 0);
  gtk_widget_show (spinTireWidth);
  gtk_table_attach (GTK_TABLE (table2), spinTireWidth, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label31 = gtk_label_new (_("height/width ratio (%)"));
  gtk_widget_show (label31);
  gtk_table_attach (GTK_TABLE (table2), label31, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label31), 0, 0.5);

  spinTireRatio_adj = gtk_adjustment_new (10, 10, 200, 1, 10, 10);
  spinTireRatio = gtk_spin_button_new (GTK_ADJUSTMENT (spinTireRatio_adj), 1, 0);
  gtk_widget_show (spinTireRatio);
  gtk_table_attach (GTK_TABLE (table2), spinTireRatio, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label24 = gtk_label_new (_("rim (inches)"));
  gtk_widget_show (label24);
  gtk_table_attach (GTK_TABLE (table2), label24, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label24), 0, 0.5);

  spinRim_adj = gtk_adjustment_new (1, 1, 50, 1, 10, 10);
  spinRim = gtk_spin_button_new (GTK_ADJUSTMENT (spinRim_adj), 1, 0);
  gtk_widget_show (spinRim);
  gtk_table_attach (GTK_TABLE (table2), spinRim, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label32 = gtk_label_new (_("total height"));
  gtk_widget_show (label32);
  gtk_table_attach (GTK_TABLE (table2), label32, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label32), 0, 0.5);

  lblWheelHeight = gtk_label_new ("0");
  gtk_widget_show (lblWheelHeight);
  gtk_table_attach (GTK_TABLE (table2), lblWheelHeight, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label33 = gtk_label_new (_("perimeter"));
  gtk_widget_show (label33);
  gtk_table_attach (GTK_TABLE (table2), label33, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label33), 0, 0.5);

  lblWheelPerimeter = gtk_label_new (_("0"));
  gtk_widget_show (lblWheelPerimeter);
  gtk_table_attach (GTK_TABLE (table2), lblWheelPerimeter, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (lblWheelPerimeter), TRUE);

  label96 = gtk_label_new (_("<b>Wheel size</b>"));
  gtk_widget_show (label96);
  gtk_expander_set_label_widget (GTK_EXPANDER (expander3), label96);
  gtk_label_set_use_markup (GTK_LABEL (label96), TRUE);

  sbMain = gtk_statusbar_new ();
  gtk_widget_show (sbMain);
  gtk_box_pack_end (GTK_BOX (vbox1), sbMain, FALSE, FALSE, 0);
  gtk_statusbar_set_has_resize_grip (GTK_STATUSBAR (sbMain), FALSE);

  g_signal_connect ((gpointer) wndMain, "show",
                    G_CALLBACK (on_wndMain_show),
                    NULL);
  g_signal_connect ((gpointer) nowy1, "activate",
                    G_CALLBACK (on_nowy1_activate),
                    NULL);
  g_signal_connect ((gpointer) otw__rz1, "activate",
                    G_CALLBACK (on_otw__rz1_activate),
                    NULL);
  g_signal_connect ((gpointer) zapisz1, "activate",
                    G_CALLBACK (on_zapisz1_activate),
                    NULL);
  g_signal_connect ((gpointer) zapisz_jako1, "activate",
                    G_CALLBACK (on_zapisz_jako1_activate),
                    NULL);
  g_signal_connect ((gpointer) zako__cz1, "activate",
                    G_CALLBACK (on_zako__cz1_activate),
                    NULL);
  g_signal_connect ((gpointer) wytnij1, "activate",
                    G_CALLBACK (on_wytnij1_activate),
                    NULL);
  g_signal_connect ((gpointer) skopiuj1, "activate",
                    G_CALLBACK (on_skopiuj1_activate),
                    NULL);
  g_signal_connect ((gpointer) wklej1, "activate",
                    G_CALLBACK (on_wklej1_activate),
                    NULL);
  g_signal_connect ((gpointer) usu__1, "activate",
                    G_CALLBACK (on_usu__1_activate),
                    NULL);
  g_signal_connect ((gpointer) graph_image_window1, "activate",
                    G_CALLBACK (on_graph_image_window1_activate),
                    NULL);
  g_signal_connect ((gpointer) informacje_o1, "activate",
                    G_CALLBACK (on_informacje_o1_activate),
                    NULL);
  g_signal_connect ((gpointer) spinWeight, "changed",
                    G_CALLBACK (on_spinWeight_changed),
                    NULL);
  g_signal_connect ((gpointer) spinMinRpm, "changed",
                    G_CALLBACK (on_spinRPM_changed),
                    NULL);
  g_signal_connect ((gpointer) spinMaxRpm, "changed",
                    G_CALLBACK (on_spinRPM_changed),
                    NULL);
  g_signal_connect ((gpointer) btnUpdate, "clicked",
                    G_CALLBACK (on_btnUpdate_clicked),
                    NULL);
  g_signal_connect ((gpointer) spinGear1, "changed",
                    G_CALLBACK (on_spinGear_changed),
                    NULL);
  g_signal_connect ((gpointer) spinGear2, "changed",
                    G_CALLBACK (on_spinGear_changed),
                    NULL);
  g_signal_connect ((gpointer) spinGear3, "changed",
                    G_CALLBACK (on_spinGear_changed),
                    NULL);
  g_signal_connect ((gpointer) spinGear4, "changed",
                    G_CALLBACK (on_spinGear_changed),
                    NULL);
  g_signal_connect ((gpointer) spinGear5, "changed",
                    G_CALLBACK (on_spinGear_changed),
                    NULL);
  g_signal_connect ((gpointer) spinGear6, "changed",
                    G_CALLBACK (on_spinGear_changed),
                    NULL);
  g_signal_connect ((gpointer) spinGear7, "changed",
                    G_CALLBACK (on_spinGear_changed),
                    NULL);
  g_signal_connect ((gpointer) scaleGears, "value_changed",
                    G_CALLBACK (on_scaleGears_value_changed),
                    NULL);
  g_signal_connect ((gpointer) spinDiffer, "changed",
                    G_CALLBACK (on_spinDiffer_changed),
                    NULL);
  g_signal_connect ((gpointer) spinTireWidth, "changed",
                    G_CALLBACK (on_spinWheel_changed),
                    NULL);
  g_signal_connect ((gpointer) spinTireRatio, "changed",
                    G_CALLBACK (on_spinWheel_changed),
                    NULL);
  g_signal_connect ((gpointer) spinRim, "changed",
                    G_CALLBACK (on_spinWheel_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (wndMain, wndMain, "wndMain");
  GLADE_HOOKUP_OBJECT (wndMain, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (wndMain, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (wndMain, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (wndMain, menuitem1_menu, "menuitem1_menu");
  GLADE_HOOKUP_OBJECT (wndMain, nowy1, "nowy1");
  GLADE_HOOKUP_OBJECT (wndMain, otw__rz1, "otw__rz1");
  GLADE_HOOKUP_OBJECT (wndMain, zapisz1, "zapisz1");
  GLADE_HOOKUP_OBJECT (wndMain, zapisz_jako1, "zapisz_jako1");
  GLADE_HOOKUP_OBJECT (wndMain, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (wndMain, zako__cz1, "zako__cz1");
  GLADE_HOOKUP_OBJECT (wndMain, menuitem2, "menuitem2");
  GLADE_HOOKUP_OBJECT (wndMain, menuitem2_menu, "menuitem2_menu");
  GLADE_HOOKUP_OBJECT (wndMain, wytnij1, "wytnij1");
  GLADE_HOOKUP_OBJECT (wndMain, skopiuj1, "skopiuj1");
  GLADE_HOOKUP_OBJECT (wndMain, wklej1, "wklej1");
  GLADE_HOOKUP_OBJECT (wndMain, usu__1, "usu__1");
  GLADE_HOOKUP_OBJECT (wndMain, menuitem3, "menuitem3");
  GLADE_HOOKUP_OBJECT (wndMain, menuitem3_menu, "menuitem3_menu");
  GLADE_HOOKUP_OBJECT (wndMain, graph_image_window1, "graph_image_window1");
  GLADE_HOOKUP_OBJECT (wndMain, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (wndMain, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (wndMain, informacje_o1, "informacje_o1");
  GLADE_HOOKUP_OBJECT (wndMain, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (wndMain, label84, "label84");
  GLADE_HOOKUP_OBJECT (wndMain, spinWeight, "spinWeight");
  GLADE_HOOKUP_OBJECT (wndMain, hseparator8, "hseparator8");
  GLADE_HOOKUP_OBJECT (wndMain, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (wndMain, label1, "label1");
  GLADE_HOOKUP_OBJECT (wndMain, label2, "label2");
  GLADE_HOOKUP_OBJECT (wndMain, spinMinRpm, "spinMinRpm");
  GLADE_HOOKUP_OBJECT (wndMain, label3, "label3");
  GLADE_HOOKUP_OBJECT (wndMain, spinMaxRpm, "spinMaxRpm");
  GLADE_HOOKUP_OBJECT (wndMain, btnUpdate, "btnUpdate");
  GLADE_HOOKUP_OBJECT (wndMain, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (wndMain, label28, "label28");
  GLADE_HOOKUP_OBJECT (wndMain, lblMaxTorque, "lblMaxTorque");
  GLADE_HOOKUP_OBJECT (wndMain, label30, "label30");
  GLADE_HOOKUP_OBJECT (wndMain, lblMaxHP, "lblMaxHP");
  GLADE_HOOKUP_OBJECT (wndMain, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (wndMain, expander2, "expander2");
  GLADE_HOOKUP_OBJECT (wndMain, vbox9, "vbox9");
  GLADE_HOOKUP_OBJECT (wndMain, table1, "table1");
  GLADE_HOOKUP_OBJECT (wndMain, spinGear1, "spinGear1");
  GLADE_HOOKUP_OBJECT (wndMain, spinGear2, "spinGear2");
  GLADE_HOOKUP_OBJECT (wndMain, spinGear3, "spinGear3");
  GLADE_HOOKUP_OBJECT (wndMain, spinGear4, "spinGear4");
  GLADE_HOOKUP_OBJECT (wndMain, spinGear5, "spinGear5");
  GLADE_HOOKUP_OBJECT (wndMain, spinGear6, "spinGear6");
  GLADE_HOOKUP_OBJECT (wndMain, spinGear7, "spinGear7");
  GLADE_HOOKUP_OBJECT (wndMain, label6, "label6");
  GLADE_HOOKUP_OBJECT (wndMain, label7, "label7");
  GLADE_HOOKUP_OBJECT (wndMain, label8, "label8");
  GLADE_HOOKUP_OBJECT (wndMain, scaleGears, "scaleGears");
  GLADE_HOOKUP_OBJECT (wndMain, label5, "label5");
  GLADE_HOOKUP_OBJECT (wndMain, label17, "label17");
  GLADE_HOOKUP_OBJECT (wndMain, label16, "label16");
  GLADE_HOOKUP_OBJECT (wndMain, label18, "label18");
  GLADE_HOOKUP_OBJECT (wndMain, label19, "label19");
  GLADE_HOOKUP_OBJECT (wndMain, label20, "label20");
  GLADE_HOOKUP_OBJECT (wndMain, label21, "label21");
  GLADE_HOOKUP_OBJECT (wndMain, label22, "label22");
  GLADE_HOOKUP_OBJECT (wndMain, lblVMin1, "lblVMin1");
  GLADE_HOOKUP_OBJECT (wndMain, lblVMin3, "lblVMin3");
  GLADE_HOOKUP_OBJECT (wndMain, lblVMin4, "lblVMin4");
  GLADE_HOOKUP_OBJECT (wndMain, lblVMin5, "lblVMin5");
  GLADE_HOOKUP_OBJECT (wndMain, lblVMin6, "lblVMin6");
  GLADE_HOOKUP_OBJECT (wndMain, lblVMin7, "lblVMin7");
  GLADE_HOOKUP_OBJECT (wndMain, lblVMax7, "lblVMax7");
  GLADE_HOOKUP_OBJECT (wndMain, lblVMax6, "lblVMax6");
  GLADE_HOOKUP_OBJECT (wndMain, lblVMax5, "lblVMax5");
  GLADE_HOOKUP_OBJECT (wndMain, lblVMax4, "lblVMax4");
  GLADE_HOOKUP_OBJECT (wndMain, lblVMax3, "lblVMax3");
  GLADE_HOOKUP_OBJECT (wndMain, lblVMax2, "lblVMax2");
  GLADE_HOOKUP_OBJECT (wndMain, lblVMax1, "lblVMax1");
  GLADE_HOOKUP_OBJECT (wndMain, lblVMin2, "lblVMin2");
  GLADE_HOOKUP_OBJECT (wndMain, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (wndMain, table3, "table3");
  GLADE_HOOKUP_OBJECT (wndMain, label27, "label27");
  GLADE_HOOKUP_OBJECT (wndMain, spinDiffer, "spinDiffer");
  GLADE_HOOKUP_OBJECT (wndMain, label26, "label26");
  GLADE_HOOKUP_OBJECT (wndMain, label95, "label95");
  GLADE_HOOKUP_OBJECT (wndMain, hseparator9, "hseparator9");
  GLADE_HOOKUP_OBJECT (wndMain, expander3, "expander3");
  GLADE_HOOKUP_OBJECT (wndMain, table2, "table2");
  GLADE_HOOKUP_OBJECT (wndMain, label23, "label23");
  GLADE_HOOKUP_OBJECT (wndMain, label25, "label25");
  GLADE_HOOKUP_OBJECT (wndMain, spinTireWidth, "spinTireWidth");
  GLADE_HOOKUP_OBJECT (wndMain, label31, "label31");
  GLADE_HOOKUP_OBJECT (wndMain, spinTireRatio, "spinTireRatio");
  GLADE_HOOKUP_OBJECT (wndMain, label24, "label24");
  GLADE_HOOKUP_OBJECT (wndMain, spinRim, "spinRim");
  GLADE_HOOKUP_OBJECT (wndMain, label32, "label32");
  GLADE_HOOKUP_OBJECT (wndMain, lblWheelHeight, "lblWheelHeight");
  GLADE_HOOKUP_OBJECT (wndMain, label33, "label33");
  GLADE_HOOKUP_OBJECT (wndMain, lblWheelPerimeter, "lblWheelPerimeter");
  GLADE_HOOKUP_OBJECT (wndMain, label96, "label96");
  GLADE_HOOKUP_OBJECT (wndMain, sbMain, "sbMain");

  gtk_window_add_accel_group (GTK_WINDOW (wndMain), accel_group);

  return wndMain;
}

GtkWidget*
create_wndTorque (void)
{
  GtkWidget *wndTorque;
  GtkWidget *vbox2;
  GtkWidget *daTorque;
  GtkWidget *hseparator4;
  GtkWidget *hbox3;
  GtkWidget *label34;
  GtkObject *spinMaxTorque_adj;
  GtkWidget *spinMaxTorque;
  GtkWidget *label35;
  GtkObject *spinMaxHP_adj;
  GtkWidget *spinMaxHP;

  wndTorque = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (wndTorque), _("Torque / Horse power"));
  gtk_window_set_default_size (GTK_WINDOW (wndTorque), -1, 280);
  gtk_window_set_gravity (GTK_WINDOW (wndTorque), GDK_GRAVITY_SOUTH_WEST);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (wndTorque), vbox2);

  daTorque = gtk_drawing_area_new ();
  gtk_widget_show (daTorque);
  gtk_box_pack_start (GTK_BOX (vbox2), daTorque, TRUE, TRUE, 0);
  gtk_widget_set_events (daTorque, GDK_EXPOSURE_MASK | GDK_POINTER_MOTION_MASK | GDK_BUTTON_MOTION_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK);

  hseparator4 = gtk_hseparator_new ();
  gtk_widget_show (hseparator4);
  gtk_box_pack_start (GTK_BOX (vbox2), hseparator4, FALSE, TRUE, 0);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox3, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox3), 2);

  label34 = gtk_label_new (_("Max Torque"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox3), label34, FALSE, FALSE, 0);

  spinMaxTorque_adj = gtk_adjustment_new (200, 5, 3000, 1, 10, 10);
  spinMaxTorque = gtk_spin_button_new (GTK_ADJUSTMENT (spinMaxTorque_adj), 1, 0);
  gtk_widget_show (spinMaxTorque);
  gtk_box_pack_start (GTK_BOX (hbox3), spinMaxTorque, TRUE, TRUE, 0);

  label35 = gtk_label_new (_("Max HP"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox3), label35, FALSE, FALSE, 0);

  spinMaxHP_adj = gtk_adjustment_new (100, 5, 2000, 1, 10, 10);
  spinMaxHP = gtk_spin_button_new (GTK_ADJUSTMENT (spinMaxHP_adj), 1, 0);
  gtk_widget_show (spinMaxHP);
  gtk_box_pack_start (GTK_BOX (hbox3), spinMaxHP, TRUE, TRUE, 0);

  g_signal_connect ((gpointer) wndTorque, "show",
                    G_CALLBACK (on_wndTorque_show),
                    NULL);
  g_signal_connect ((gpointer) daTorque, "configure_event",
                    G_CALLBACK (on_daTorque_configure_event),
                    NULL);
  g_signal_connect ((gpointer) daTorque, "expose_event",
                    G_CALLBACK (on_daTorque_expose_event),
                    NULL);
  g_signal_connect ((gpointer) daTorque, "button_press_event",
                    G_CALLBACK (on_daTorque_button_event),
                    NULL);
  g_signal_connect ((gpointer) daTorque, "button_release_event",
                    G_CALLBACK (on_daTorque_button_event),
                    NULL);
  g_signal_connect ((gpointer) daTorque, "motion_notify_event",
                    G_CALLBACK (on_daTorque_button_event),
                    NULL);
  g_signal_connect ((gpointer) spinMaxTorque, "changed",
                    G_CALLBACK (on_spinMaxTHP_changed),
                    NULL);
  g_signal_connect ((gpointer) spinMaxHP, "changed",
                    G_CALLBACK (on_spinMaxTHP_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (wndTorque, wndTorque, "wndTorque");
  GLADE_HOOKUP_OBJECT (wndTorque, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (wndTorque, daTorque, "daTorque");
  GLADE_HOOKUP_OBJECT (wndTorque, hseparator4, "hseparator4");
  GLADE_HOOKUP_OBJECT (wndTorque, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (wndTorque, label34, "label34");
  GLADE_HOOKUP_OBJECT (wndTorque, spinMaxTorque, "spinMaxTorque");
  GLADE_HOOKUP_OBJECT (wndTorque, label35, "label35");
  GLADE_HOOKUP_OBJECT (wndTorque, spinMaxHP, "spinMaxHP");

  return wndTorque;
}

GtkWidget*
create_wndWheelForce (void)
{
  GtkWidget *wndWheelForce;
  GtkWidget *vbox3;
  GtkWidget *daWheelForce;
  GtkWidget *hseparator5;
  GtkWidget *hbox4;
  GtkWidget *label36;
  GtkObject *spinMaxWForce_adj;
  GtkWidget *spinMaxWForce;
  GtkWidget *label38;
  GtkObject *spinMaxSpeed_adj;
  GtkWidget *spinMaxSpeed;

  wndWheelForce = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (wndWheelForce), _("Force at Wheels"));
  gtk_window_set_default_size (GTK_WINDOW (wndWheelForce), 322, 202);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (wndWheelForce), vbox3);

  daWheelForce = gtk_drawing_area_new ();
  gtk_widget_show (daWheelForce);
  gtk_box_pack_start (GTK_BOX (vbox3), daWheelForce, TRUE, TRUE, 0);
  gtk_widget_set_events (daWheelForce, GDK_EXPOSURE_MASK);

  hseparator5 = gtk_hseparator_new ();
  gtk_widget_show (hseparator5);
  gtk_box_pack_start (GTK_BOX (vbox3), hseparator5, FALSE, TRUE, 0);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox4, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox4), 2);

  label36 = gtk_label_new (_("Max Wheel Force"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox4), label36, FALSE, FALSE, 0);

  spinMaxWForce_adj = gtk_adjustment_new (150, 0, 1000, 1, 10, 10);
  spinMaxWForce = gtk_spin_button_new (GTK_ADJUSTMENT (spinMaxWForce_adj), 1, 0);
  gtk_widget_show (spinMaxWForce);
  gtk_box_pack_start (GTK_BOX (hbox4), spinMaxWForce, TRUE, TRUE, 0);

  label38 = gtk_label_new (_("Max Speed"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox4), label38, FALSE, FALSE, 0);

  spinMaxSpeed_adj = gtk_adjustment_new (250, 50, 500, 1, 10, 10);
  spinMaxSpeed = gtk_spin_button_new (GTK_ADJUSTMENT (spinMaxSpeed_adj), 1, 0);
  gtk_widget_show (spinMaxSpeed);
  gtk_box_pack_start (GTK_BOX (hbox4), spinMaxSpeed, TRUE, TRUE, 0);

  g_signal_connect ((gpointer) daWheelForce, "configure_event",
                    G_CALLBACK (on_daWheelForce_configure_event),
                    NULL);
  g_signal_connect ((gpointer) daWheelForce, "expose_event",
                    G_CALLBACK (on_daWheelForce_expose_event),
                    NULL);
  g_signal_connect ((gpointer) spinMaxWForce, "changed",
                    G_CALLBACK (on_spinWForce_changed),
                    NULL);
  g_signal_connect ((gpointer) spinMaxSpeed, "changed",
                    G_CALLBACK (on_spinWForce_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (wndWheelForce, wndWheelForce, "wndWheelForce");
  GLADE_HOOKUP_OBJECT (wndWheelForce, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (wndWheelForce, daWheelForce, "daWheelForce");
  GLADE_HOOKUP_OBJECT (wndWheelForce, hseparator5, "hseparator5");
  GLADE_HOOKUP_OBJECT (wndWheelForce, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (wndWheelForce, label36, "label36");
  GLADE_HOOKUP_OBJECT (wndWheelForce, spinMaxWForce, "spinMaxWForce");
  GLADE_HOOKUP_OBJECT (wndWheelForce, label38, "label38");
  GLADE_HOOKUP_OBJECT (wndWheelForce, spinMaxSpeed, "spinMaxSpeed");

  return wndWheelForce;
}

GtkWidget*
create_wndTime (void)
{
  GtkWidget *wndTime;
  GtkWidget *vbox4;
  GtkWidget *daTime;
  GtkWidget *hseparator6;
  GtkWidget *hbox5;
  GtkWidget *label42;
  GtkObject *spinTAccel_adj;
  GtkWidget *spinTAccel;
  GtkWidget *label39;
  GtkObject *spinTSpeed_adj;
  GtkWidget *spinTSpeed;
  GtkWidget *label40;
  GtkObject *spinTRoad_adj;
  GtkWidget *spinTRoad;
  GtkWidget *label41;
  GtkObject *spinTSeconds_adj;
  GtkWidget *spinTSeconds;

  wndTime = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (wndTime), _("Speed / Road"));
  gtk_window_set_default_size (GTK_WINDOW (wndTime), 400, 350);

  vbox4 = gtk_vbox_new (FALSE, 2);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (wndTime), vbox4);

  daTime = gtk_drawing_area_new ();
  gtk_widget_show (daTime);
  gtk_box_pack_start (GTK_BOX (vbox4), daTime, TRUE, TRUE, 0);
  gtk_widget_set_events (daTime, GDK_EXPOSURE_MASK);

  hseparator6 = gtk_hseparator_new ();
  gtk_widget_show (hseparator6);
  gtk_box_pack_start (GTK_BOX (vbox4), hseparator6, FALSE, TRUE, 0);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox5, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox5), 2);

  label42 = gtk_label_new (_("Max Accel"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox5), label42, FALSE, FALSE, 0);

  spinTAccel_adj = gtk_adjustment_new (8, 0.10000000149, 40, 0.10000000149, 10, 10);
  spinTAccel = gtk_spin_button_new (GTK_ADJUSTMENT (spinTAccel_adj), 1, 1);
  gtk_widget_show (spinTAccel);
  gtk_box_pack_start (GTK_BOX (hbox5), spinTAccel, TRUE, TRUE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinTAccel), TRUE);

  label39 = gtk_label_new (_("Max Speed"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox5), label39, FALSE, FALSE, 0);

  spinTSpeed_adj = gtk_adjustment_new (250, 20, 600, 1, 10, 10);
  spinTSpeed = gtk_spin_button_new (GTK_ADJUSTMENT (spinTSpeed_adj), 1, 0);
  gtk_widget_show (spinTSpeed);
  gtk_box_pack_start (GTK_BOX (hbox5), spinTSpeed, TRUE, TRUE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinTSpeed), TRUE);

  label40 = gtk_label_new (_("Max Road"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox5), label40, FALSE, FALSE, 0);

  spinTRoad_adj = gtk_adjustment_new (1000, 100, 10000, 1, 10, 10);
  spinTRoad = gtk_spin_button_new (GTK_ADJUSTMENT (spinTRoad_adj), 1, 0);
  gtk_widget_show (spinTRoad);
  gtk_box_pack_start (GTK_BOX (hbox5), spinTRoad, TRUE, TRUE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinTRoad), TRUE);

  label41 = gtk_label_new (_("Seconds"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox5), label41, FALSE, FALSE, 0);

  spinTSeconds_adj = gtk_adjustment_new (26, 1, 130, 1, 10, 10);
  spinTSeconds = gtk_spin_button_new (GTK_ADJUSTMENT (spinTSeconds_adj), 1, 0);
  gtk_widget_show (spinTSeconds);
  gtk_box_pack_start (GTK_BOX (hbox5), spinTSeconds, TRUE, TRUE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinTSeconds), TRUE);

  g_signal_connect ((gpointer) daTime, "configure_event",
                    G_CALLBACK (on_daTime_configure_event),
                    NULL);
  g_signal_connect ((gpointer) daTime, "expose_event",
                    G_CALLBACK (on_daTime_expose_event),
                    NULL);
  g_signal_connect ((gpointer) spinTAccel, "changed",
                    G_CALLBACK (on_spinTime_changed),
                    NULL);
  g_signal_connect ((gpointer) spinTSpeed, "changed",
                    G_CALLBACK (on_spinTime_changed),
                    NULL);
  g_signal_connect ((gpointer) spinTRoad, "changed",
                    G_CALLBACK (on_spinTime_changed),
                    NULL);
  g_signal_connect ((gpointer) spinTSeconds, "changed",
                    G_CALLBACK (on_spinTSeconds_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (wndTime, wndTime, "wndTime");
  GLADE_HOOKUP_OBJECT (wndTime, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (wndTime, daTime, "daTime");
  GLADE_HOOKUP_OBJECT (wndTime, hseparator6, "hseparator6");
  GLADE_HOOKUP_OBJECT (wndTime, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (wndTime, label42, "label42");
  GLADE_HOOKUP_OBJECT (wndTime, spinTAccel, "spinTAccel");
  GLADE_HOOKUP_OBJECT (wndTime, label39, "label39");
  GLADE_HOOKUP_OBJECT (wndTime, spinTSpeed, "spinTSpeed");
  GLADE_HOOKUP_OBJECT (wndTime, label40, "label40");
  GLADE_HOOKUP_OBJECT (wndTime, spinTRoad, "spinTRoad");
  GLADE_HOOKUP_OBJECT (wndTime, label41, "label41");
  GLADE_HOOKUP_OBJECT (wndTime, spinTSeconds, "spinTSeconds");

  return wndTime;
}

GtkWidget*
create_wndPerf (void)
{
  GtkWidget *wndPerf;
  GtkWidget *table4;
  GtkWidget *label46;
  GtkWidget *label47;
  GtkWidget *label48;
  GtkWidget *label49;
  GtkWidget *label50;
  GtkWidget *label51;
  GtkWidget *label52;
  GtkWidget *label53;
  GtkWidget *label54;
  GtkWidget *label55;
  GtkWidget *label56;
  GtkWidget *label57;
  GtkWidget *label58;
  GtkWidget *label59;
  GtkWidget *label60;
  GtkWidget *label61;
  GtkWidget *label62;
  GtkWidget *label63;
  GtkWidget *hseparator7;
  GtkWidget *lblTV0;
  GtkWidget *lblTV1;
  GtkWidget *lblTV2;
  GtkWidget *lblTV3;
  GtkWidget *lblTV5;
  GtkWidget *lblTV4;
  GtkWidget *lblTV6;
  GtkWidget *lblTV7;
  GtkWidget *lblTV8;
  GtkWidget *lblTV9;
  GtkWidget *lblTV10;
  GtkWidget *lblTS6;
  GtkWidget *lblTS5;
  GtkWidget *lblTS4;
  GtkWidget *lblTS3;
  GtkWidget *lblTS2;
  GtkWidget *lblTS1;
  GtkWidget *lblTS0;
  GtkWidget *label43;
  GtkWidget *label44;
  GtkWidget *label45;
  GtkWidget *label83;
  GtkWidget *lblTV11;

  wndPerf = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (wndPerf), _("Timings"));
  gtk_window_set_resizable (GTK_WINDOW (wndPerf), FALSE);
  gtk_window_set_skip_taskbar_hint (GTK_WINDOW (wndPerf), TRUE);

  table4 = gtk_table_new (15, 4, FALSE);
  gtk_widget_show (table4);
  gtk_container_add (GTK_CONTAINER (wndPerf), table4);
  gtk_container_set_border_width (GTK_CONTAINER (table4), 2);
  gtk_table_set_row_spacings (GTK_TABLE (table4), 1);
  gtk_table_set_col_spacings (GTK_TABLE (table4), 5);

  label46 = gtk_label_new (_("20 km/h"));
  gtk_widget_show (label46);
  gtk_table_attach (GTK_TABLE (table4), label46, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label46), 0, 0.5);

  label47 = gtk_label_new (_("40 km/h"));
  gtk_widget_show (label47);
  gtk_table_attach (GTK_TABLE (table4), label47, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label47), 0, 0.5);

  label48 = gtk_label_new (_("60 km/h"));
  gtk_widget_show (label48);
  gtk_table_attach (GTK_TABLE (table4), label48, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label48), 0, 0.5);

  label49 = gtk_label_new (_("80 km/h"));
  gtk_widget_show (label49);
  gtk_table_attach (GTK_TABLE (table4), label49, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label49), 0, 0.5);

  label50 = gtk_label_new (_("100 km/h"));
  gtk_widget_show (label50);
  gtk_table_attach (GTK_TABLE (table4), label50, 0, 1, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label50), 0, 0.5);

  label51 = gtk_label_new (_("120 km/h"));
  gtk_widget_show (label51);
  gtk_table_attach (GTK_TABLE (table4), label51, 0, 1, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label51), 0, 0.5);

  label52 = gtk_label_new (_("150 km/h"));
  gtk_widget_show (label52);
  gtk_table_attach (GTK_TABLE (table4), label52, 0, 1, 9, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label52), 0, 0.5);

  label53 = gtk_label_new (_("100 mph"));
  gtk_widget_show (label53);
  gtk_table_attach (GTK_TABLE (table4), label53, 0, 1, 10, 11,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label53), 0, 0.5);

  label54 = gtk_label_new (_("200 km/h"));
  gtk_widget_show (label54);
  gtk_table_attach (GTK_TABLE (table4), label54, 0, 1, 11, 12,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label54), 0, 0.5);

  label55 = gtk_label_new (_("250 km/h"));
  gtk_widget_show (label55);
  gtk_table_attach (GTK_TABLE (table4), label55, 0, 1, 12, 13,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label55), 0, 0.5);

  label56 = gtk_label_new (_("300 km/h"));
  gtk_widget_show (label56);
  gtk_table_attach (GTK_TABLE (table4), label56, 0, 1, 13, 14,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label56), 0, 0.5);

  label57 = gtk_label_new (_("10 m"));
  gtk_widget_show (label57);
  gtk_table_attach (GTK_TABLE (table4), label57, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label57), 0, 0.5);

  label58 = gtk_label_new (_("100 m"));
  gtk_widget_show (label58);
  gtk_table_attach (GTK_TABLE (table4), label58, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label58), 0, 0.5);

  label59 = gtk_label_new (_("1/8 mile"));
  gtk_widget_show (label59);
  gtk_table_attach (GTK_TABLE (table4), label59, 2, 3, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label59), 0, 0.5);

  label60 = gtk_label_new (_("1/4 mile"));
  gtk_widget_show (label60);
  gtk_table_attach (GTK_TABLE (table4), label60, 2, 3, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label60), 0, 0.5);

  label61 = gtk_label_new (_("500 m"));
  gtk_widget_show (label61);
  gtk_table_attach (GTK_TABLE (table4), label61, 2, 3, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label61), 0, 0.5);

  label62 = gtk_label_new (_("1000 m"));
  gtk_widget_show (label62);
  gtk_table_attach (GTK_TABLE (table4), label62, 2, 3, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label62), 0, 0.5);

  label63 = gtk_label_new (_("1 mile"));
  gtk_widget_show (label63);
  gtk_table_attach (GTK_TABLE (table4), label63, 2, 3, 9, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label63), 0, 0.5);

  hseparator7 = gtk_hseparator_new ();
  gtk_widget_show (hseparator7);
  gtk_table_attach (GTK_TABLE (table4), hseparator7, 0, 4, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  lblTV0 = gtk_label_new (_("0"));
  gtk_widget_show (lblTV0);
  gtk_table_attach (GTK_TABLE (table4), lblTV0, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblTV0), 1, 0.5);

  lblTV1 = gtk_label_new (_("0"));
  gtk_widget_show (lblTV1);
  gtk_table_attach (GTK_TABLE (table4), lblTV1, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblTV1), 1, 0.5);

  lblTV2 = gtk_label_new (_("0"));
  gtk_widget_show (lblTV2);
  gtk_table_attach (GTK_TABLE (table4), lblTV2, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblTV2), 1, 0.5);

  lblTV3 = gtk_label_new (_("0"));
  gtk_widget_show (lblTV3);
  gtk_table_attach (GTK_TABLE (table4), lblTV3, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblTV3), 1, 0.5);

  lblTV5 = gtk_label_new (_("0"));
  gtk_widget_show (lblTV5);
  gtk_table_attach (GTK_TABLE (table4), lblTV5, 1, 2, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblTV5), 1, 0.5);

  lblTV4 = gtk_label_new (_("0"));
  gtk_widget_show (lblTV4);
  gtk_table_attach (GTK_TABLE (table4), lblTV4, 1, 2, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblTV4), 1, 0.5);

  lblTV6 = gtk_label_new (_("0"));
  gtk_widget_show (lblTV6);
  gtk_table_attach (GTK_TABLE (table4), lblTV6, 1, 2, 9, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblTV6), 1, 0.5);

  lblTV7 = gtk_label_new (_("0"));
  gtk_widget_show (lblTV7);
  gtk_table_attach (GTK_TABLE (table4), lblTV7, 1, 2, 10, 11,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblTV7), 1, 0.5);

  lblTV8 = gtk_label_new (_("0"));
  gtk_widget_show (lblTV8);
  gtk_table_attach (GTK_TABLE (table4), lblTV8, 1, 2, 11, 12,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblTV8), 1, 0.5);

  lblTV9 = gtk_label_new (_("0"));
  gtk_widget_show (lblTV9);
  gtk_table_attach (GTK_TABLE (table4), lblTV9, 1, 2, 12, 13,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblTV9), 1, 0.5);

  lblTV10 = gtk_label_new (_("0"));
  gtk_widget_show (lblTV10);
  gtk_table_attach (GTK_TABLE (table4), lblTV10, 1, 2, 13, 14,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblTV10), 1, 0.5);

  lblTS6 = gtk_label_new (_("0"));
  gtk_widget_show (lblTS6);
  gtk_table_attach (GTK_TABLE (table4), lblTS6, 3, 4, 9, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblTS6), 1, 0.5);

  lblTS5 = gtk_label_new (_("0"));
  gtk_widget_show (lblTS5);
  gtk_table_attach (GTK_TABLE (table4), lblTS5, 3, 4, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblTS5), 1, 0.5);

  lblTS4 = gtk_label_new (_("0"));
  gtk_widget_show (lblTS4);
  gtk_table_attach (GTK_TABLE (table4), lblTS4, 3, 4, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblTS4), 1, 0.5);

  lblTS3 = gtk_label_new (_("0"));
  gtk_widget_show (lblTS3);
  gtk_table_attach (GTK_TABLE (table4), lblTS3, 3, 4, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblTS3), 1, 0.5);

  lblTS2 = gtk_label_new (_("0"));
  gtk_widget_show (lblTS2);
  gtk_table_attach (GTK_TABLE (table4), lblTS2, 3, 4, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblTS2), 1, 0.5);

  lblTS1 = gtk_label_new (_("0"));
  gtk_widget_show (lblTS1);
  gtk_table_attach (GTK_TABLE (table4), lblTS1, 3, 4, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblTS1), 1, 0.5);

  lblTS0 = gtk_label_new (_("0"));
  gtk_widget_show (lblTS0);
  gtk_table_attach (GTK_TABLE (table4), lblTS0, 3, 4, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblTS0), 1, 0.5);

  label43 = gtk_label_new (_("<big>Performance</big>"));
  gtk_widget_show (label43);
  gtk_table_attach (GTK_TABLE (table4), label43, 0, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label43), TRUE);

  label44 = gtk_label_new (_("<b>Speed</b>"));
  gtk_widget_show (label44);
  gtk_table_attach (GTK_TABLE (table4), label44, 0, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label44), TRUE);

  label45 = gtk_label_new (_("<b>Distance</b>"));
  gtk_widget_show (label45);
  gtk_table_attach (GTK_TABLE (table4), label45, 2, 4, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label45), TRUE);

  label83 = gtk_label_new (_("200 mph"));
  gtk_widget_show (label83);
  gtk_table_attach (GTK_TABLE (table4), label83, 0, 1, 14, 15,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label83), 0, 0.5);

  lblTV11 = gtk_label_new (_("0"));
  gtk_widget_show (lblTV11);
  gtk_table_attach (GTK_TABLE (table4), lblTV11, 1, 2, 14, 15,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (lblTV11), 1, 0.5);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (wndPerf, wndPerf, "wndPerf");
  GLADE_HOOKUP_OBJECT (wndPerf, table4, "table4");
  GLADE_HOOKUP_OBJECT (wndPerf, label46, "label46");
  GLADE_HOOKUP_OBJECT (wndPerf, label47, "label47");
  GLADE_HOOKUP_OBJECT (wndPerf, label48, "label48");
  GLADE_HOOKUP_OBJECT (wndPerf, label49, "label49");
  GLADE_HOOKUP_OBJECT (wndPerf, label50, "label50");
  GLADE_HOOKUP_OBJECT (wndPerf, label51, "label51");
  GLADE_HOOKUP_OBJECT (wndPerf, label52, "label52");
  GLADE_HOOKUP_OBJECT (wndPerf, label53, "label53");
  GLADE_HOOKUP_OBJECT (wndPerf, label54, "label54");
  GLADE_HOOKUP_OBJECT (wndPerf, label55, "label55");
  GLADE_HOOKUP_OBJECT (wndPerf, label56, "label56");
  GLADE_HOOKUP_OBJECT (wndPerf, label57, "label57");
  GLADE_HOOKUP_OBJECT (wndPerf, label58, "label58");
  GLADE_HOOKUP_OBJECT (wndPerf, label59, "label59");
  GLADE_HOOKUP_OBJECT (wndPerf, label60, "label60");
  GLADE_HOOKUP_OBJECT (wndPerf, label61, "label61");
  GLADE_HOOKUP_OBJECT (wndPerf, label62, "label62");
  GLADE_HOOKUP_OBJECT (wndPerf, label63, "label63");
  GLADE_HOOKUP_OBJECT (wndPerf, hseparator7, "hseparator7");
  GLADE_HOOKUP_OBJECT (wndPerf, lblTV0, "lblTV0");
  GLADE_HOOKUP_OBJECT (wndPerf, lblTV1, "lblTV1");
  GLADE_HOOKUP_OBJECT (wndPerf, lblTV2, "lblTV2");
  GLADE_HOOKUP_OBJECT (wndPerf, lblTV3, "lblTV3");
  GLADE_HOOKUP_OBJECT (wndPerf, lblTV5, "lblTV5");
  GLADE_HOOKUP_OBJECT (wndPerf, lblTV4, "lblTV4");
  GLADE_HOOKUP_OBJECT (wndPerf, lblTV6, "lblTV6");
  GLADE_HOOKUP_OBJECT (wndPerf, lblTV7, "lblTV7");
  GLADE_HOOKUP_OBJECT (wndPerf, lblTV8, "lblTV8");
  GLADE_HOOKUP_OBJECT (wndPerf, lblTV9, "lblTV9");
  GLADE_HOOKUP_OBJECT (wndPerf, lblTV10, "lblTV10");
  GLADE_HOOKUP_OBJECT (wndPerf, lblTS6, "lblTS6");
  GLADE_HOOKUP_OBJECT (wndPerf, lblTS5, "lblTS5");
  GLADE_HOOKUP_OBJECT (wndPerf, lblTS4, "lblTS4");
  GLADE_HOOKUP_OBJECT (wndPerf, lblTS3, "lblTS3");
  GLADE_HOOKUP_OBJECT (wndPerf, lblTS2, "lblTS2");
  GLADE_HOOKUP_OBJECT (wndPerf, lblTS1, "lblTS1");
  GLADE_HOOKUP_OBJECT (wndPerf, lblTS0, "lblTS0");
  GLADE_HOOKUP_OBJECT (wndPerf, label43, "label43");
  GLADE_HOOKUP_OBJECT (wndPerf, label44, "label44");
  GLADE_HOOKUP_OBJECT (wndPerf, label45, "label45");
  GLADE_HOOKUP_OBJECT (wndPerf, label83, "label83");
  GLADE_HOOKUP_OBJECT (wndPerf, lblTV11, "lblTV11");

  return wndPerf;
}

GtkWidget*
create_wndImgGraph (void)
{
  GtkWidget *wndImgGraph;
  GtkWidget *hbox7;
  GtkWidget *vbox6;
  GtkWidget *btnCopyCar;
  GtkWidget *alignment6;
  GtkWidget *hbox13;
  GtkWidget *image6;
  GtkWidget *label90;
  GtkWidget *btnFillCurve;
  GtkWidget *expander1;
  GtkWidget *vbox8;
  GtkWidget *tglPath;
  GtkWidget *tglCalibr1;
  GtkWidget *tglCalibr2;
  GtkWidget *tglCalibr3;
  GtkWidget *table6;
  GtkWidget *label91;
  GtkObject *spnCalibrRpm_adj;
  GtkWidget *spnCalibrRpm;
  GtkWidget *label93;
  GtkObject *spnCalibrValue_adj;
  GtkWidget *spnCalibrValue;
  GtkWidget *label94;
  GtkWidget *viewport1;
  GtkWidget *draZoom;
  GtkWidget *vseparator1;
  GtkWidget *scrolledwindow1;
  GtkWidget *viewport2;
  GtkWidget *draImgGraph;

  wndImgGraph = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_container_set_border_width (GTK_CONTAINER (wndImgGraph), 2);
  gtk_window_set_title (GTK_WINDOW (wndImgGraph), _("Graph from img"));

  hbox7 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (wndImgGraph), hbox7);

  vbox6 = gtk_vbox_new (FALSE, 2);
  gtk_widget_show (vbox6);
  gtk_box_pack_start (GTK_BOX (hbox7), vbox6, FALSE, FALSE, 0);

  btnCopyCar = gtk_button_new ();
  gtk_widget_show (btnCopyCar);
  gtk_box_pack_start (GTK_BOX (vbox6), btnCopyCar, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (btnCopyCar, GTK_CAN_DEFAULT);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (btnCopyCar), alignment6);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox13);

  image6 = gtk_image_new_from_stock ("gtk-copy", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox13), image6, FALSE, FALSE, 0);

  label90 = gtk_label_new_with_mnemonic (_("Copy to car"));
  gtk_widget_show (label90);
  gtk_box_pack_start (GTK_BOX (hbox13), label90, FALSE, FALSE, 0);

  btnFillCurve = gtk_button_new_with_mnemonic (_("Fill curve"));
  gtk_widget_show (btnFillCurve);
  gtk_box_pack_start (GTK_BOX (vbox6), btnFillCurve, FALSE, FALSE, 0);

  expander1 = gtk_expander_new (NULL);
  gtk_widget_show (expander1);
  gtk_box_pack_start (GTK_BOX (vbox6), expander1, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (expander1), 2);
  gtk_expander_set_expanded (GTK_EXPANDER (expander1), TRUE);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox8);
  gtk_container_add (GTK_CONTAINER (expander1), vbox8);

  tglPath = gtk_toggle_button_new_with_mnemonic (_("Path"));
  gtk_widget_show (tglPath);
  gtk_box_pack_start (GTK_BOX (vbox8), tglPath, FALSE, FALSE, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (tglPath), FALSE);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (tglPath), TRUE);

  tglCalibr1 = gtk_toggle_button_new_with_mnemonic (_("Calibraton #1"));
  gtk_widget_show (tglCalibr1);
  gtk_box_pack_start (GTK_BOX (vbox8), tglCalibr1, FALSE, FALSE, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (tglCalibr1), FALSE);

  tglCalibr2 = gtk_toggle_button_new_with_mnemonic (_("Calibraton #2"));
  gtk_widget_show (tglCalibr2);
  gtk_box_pack_start (GTK_BOX (vbox8), tglCalibr2, FALSE, FALSE, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (tglCalibr2), FALSE);

  tglCalibr3 = gtk_toggle_button_new_with_mnemonic (_("Calibration #3"));
  gtk_widget_show (tglCalibr3);
  gtk_box_pack_start (GTK_BOX (vbox8), tglCalibr3, FALSE, FALSE, 0);
  gtk_button_set_focus_on_click (GTK_BUTTON (tglCalibr3), FALSE);

  table6 = gtk_table_new (2, 2, FALSE);
  gtk_widget_show (table6);
  gtk_box_pack_start (GTK_BOX (vbox8), table6, TRUE, TRUE, 0);

  label91 = gtk_label_new (_("RPM"));
  gtk_widget_show (label91);
  gtk_table_attach (GTK_TABLE (table6), label91, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label91), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label91), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (label91), 3, 0);

  spnCalibrRpm_adj = gtk_adjustment_new (0, 0, 25000, 1, 10, 10);
  spnCalibrRpm = gtk_spin_button_new (GTK_ADJUSTMENT (spnCalibrRpm_adj), 1, 0);
  gtk_widget_show (spnCalibrRpm);
  gtk_table_attach (GTK_TABLE (table6), spnCalibrRpm, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label93 = gtk_label_new (_("value"));
  gtk_widget_show (label93);
  gtk_table_attach (GTK_TABLE (table6), label93, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label93), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label93), 1, 0.5);
  gtk_misc_set_padding (GTK_MISC (label93), 3, 0);

  spnCalibrValue_adj = gtk_adjustment_new (0, 0, 8000, 1, 10, 10);
  spnCalibrValue = gtk_spin_button_new (GTK_ADJUSTMENT (spnCalibrValue_adj), 1, 1);
  gtk_widget_show (spnCalibrValue);
  gtk_table_attach (GTK_TABLE (table6), spnCalibrValue, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label94 = gtk_label_new (_("Mode"));
  gtk_widget_show (label94);
  gtk_expander_set_label_widget (GTK_EXPANDER (expander1), label94);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_box_pack_start (GTK_BOX (vbox6), viewport1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (viewport1), 1);
  gtk_viewport_set_shadow_type (GTK_VIEWPORT (viewport1), GTK_SHADOW_ETCHED_IN);

  draZoom = gtk_drawing_area_new ();
  gtk_widget_show (draZoom);
  gtk_container_add (GTK_CONTAINER (viewport1), draZoom);
  gtk_widget_set_events (draZoom, GDK_EXPOSURE_MASK);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_box_pack_start (GTK_BOX (hbox7), vseparator1, FALSE, TRUE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (hbox7), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  viewport2 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), viewport2);

  draImgGraph = gtk_drawing_area_new ();
  gtk_widget_show (draImgGraph);
  gtk_container_add (GTK_CONTAINER (viewport2), draImgGraph);
  gtk_widget_set_events (draImgGraph, GDK_EXPOSURE_MASK | GDK_POINTER_MOTION_MASK | GDK_BUTTON_MOTION_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK);

  g_signal_connect ((gpointer) btnCopyCar, "clicked",
                    G_CALLBACK (on_btnCopyCar_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnFillCurve, "clicked",
                    G_CALLBACK (on_btnFillCurve_clicked),
                    NULL);
  g_signal_connect ((gpointer) tglPath, "toggled",
                    G_CALLBACK (on_tglPath_toggled),
                    NULL);
  g_signal_connect ((gpointer) tglCalibr1, "toggled",
                    G_CALLBACK (on_tglCalibr1_toggled),
                    NULL);
  g_signal_connect ((gpointer) tglCalibr2, "toggled",
                    G_CALLBACK (on_tglCalibr2_toggled),
                    NULL);
  g_signal_connect ((gpointer) tglCalibr3, "toggled",
                    G_CALLBACK (on_tglCalibr3_toggled),
                    NULL);
  g_signal_connect ((gpointer) spnCalibrRpm, "value_changed",
                    G_CALLBACK (on_spnCalibrRpm_value_changed),
                    NULL);
  g_signal_connect ((gpointer) spnCalibrValue, "value_changed",
                    G_CALLBACK (on_spnCalibrValue_value_changed),
                    NULL);
  g_signal_connect ((gpointer) draZoom, "expose_event",
                    G_CALLBACK (on_draZoom_expose_event),
                    NULL);
  g_signal_connect ((gpointer) draZoom, "configure_event",
                    G_CALLBACK (on_draZoom_configure_event),
                    NULL);
  g_signal_connect ((gpointer) draImgGraph, "configure_event",
                    G_CALLBACK (on_draImgGraph_configure_event),
                    NULL);
  g_signal_connect ((gpointer) draImgGraph, "button_press_event",
                    G_CALLBACK (on_draImgGraph_button_event),
                    NULL);
  g_signal_connect ((gpointer) draImgGraph, "button_release_event",
                    G_CALLBACK (on_draImgGraph_button_event),
                    NULL);
  g_signal_connect ((gpointer) draImgGraph, "motion_notify_event",
                    G_CALLBACK (on_draImgGraph_button_event),
                    NULL);
  g_signal_connect ((gpointer) draImgGraph, "expose_event",
                    G_CALLBACK (on_draImgGraph_expose_event),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (wndImgGraph, wndImgGraph, "wndImgGraph");
  GLADE_HOOKUP_OBJECT (wndImgGraph, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (wndImgGraph, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (wndImgGraph, btnCopyCar, "btnCopyCar");
  GLADE_HOOKUP_OBJECT (wndImgGraph, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (wndImgGraph, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (wndImgGraph, image6, "image6");
  GLADE_HOOKUP_OBJECT (wndImgGraph, label90, "label90");
  GLADE_HOOKUP_OBJECT (wndImgGraph, btnFillCurve, "btnFillCurve");
  GLADE_HOOKUP_OBJECT (wndImgGraph, expander1, "expander1");
  GLADE_HOOKUP_OBJECT (wndImgGraph, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (wndImgGraph, tglPath, "tglPath");
  GLADE_HOOKUP_OBJECT (wndImgGraph, tglCalibr1, "tglCalibr1");
  GLADE_HOOKUP_OBJECT (wndImgGraph, tglCalibr2, "tglCalibr2");
  GLADE_HOOKUP_OBJECT (wndImgGraph, tglCalibr3, "tglCalibr3");
  GLADE_HOOKUP_OBJECT (wndImgGraph, table6, "table6");
  GLADE_HOOKUP_OBJECT (wndImgGraph, label91, "label91");
  GLADE_HOOKUP_OBJECT (wndImgGraph, spnCalibrRpm, "spnCalibrRpm");
  GLADE_HOOKUP_OBJECT (wndImgGraph, label93, "label93");
  GLADE_HOOKUP_OBJECT (wndImgGraph, spnCalibrValue, "spnCalibrValue");
  GLADE_HOOKUP_OBJECT (wndImgGraph, label94, "label94");
  GLADE_HOOKUP_OBJECT (wndImgGraph, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (wndImgGraph, draZoom, "draZoom");
  GLADE_HOOKUP_OBJECT (wndImgGraph, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (wndImgGraph, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (wndImgGraph, viewport2, "viewport2");
  GLADE_HOOKUP_OBJECT (wndImgGraph, draImgGraph, "draImgGraph");

  return wndImgGraph;
}

